import { useEffect, useMemo, useState } from 'react';
import { destinations, states as destinationStates } from './data/destinations';
import { budgets, climates, days, interests, states, travelTypes } from './data/preferences';
import { getRecommendations, matchLabel, scoreDestination } from './utils/recommendationEngine';

const emptyPreferences = { state:'Any State', budget:'', days:'', climate:'', interests:[], travelType:'' };
function readStoredJSON(key,fallback) { try { const raw=localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; } }
function readStoredText(key,fallback) { try { return localStorage.getItem(key)||fallback; } catch { return fallback; } }
function writeStored(key,value) { try { localStorage.setItem(key,value); } catch { /* Storage can be unavailable in private browsing. */ } }
const icons = { Adventure:'↗', Beaches:'≈', Nature:'⌁', History:'◈', Shopping:'◇', Culture:'✦', Wildlife:'◌', Food:'⌁' };
const navItems = [['/','Home'],['/explore','Explore States'],['/how-it-works','How It Works'],['/about','About Us'],['/contact','Contact']];

const BASE_PATH = '/TravelMate';

function navigate(path) {
  const target = path === '/' ? `${BASE_PATH}/` : `${BASE_PATH}${path}`;
  window.history.pushState({}, '', target);
  window.dispatchEvent(new PopStateEvent('popstate'));
  window.scrollTo(0, 0);
} }
function useRoute() { const [route,setRoute] = useState(window.location.pathname); useEffect(() => { const fn=()=>setRoute(window.location.pathname); window.addEventListener('popstate',fn); return ()=>window.removeEventListener('popstate',fn); },[]); return route; }
function useReveal(route) { useEffect(() => { const items=[...document.querySelectorAll('main section, .page > *, .detail-content')]; items.forEach(item=>item.classList.add('reveal-item')); if(!('IntersectionObserver' in window)){items.forEach(item=>item.classList.add('is-visible'));return;} const observer=new IntersectionObserver((entries)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.14,rootMargin:'0px 0px -28px'}); items.forEach((item,index)=>{item.style.setProperty('--reveal-delay',`${Math.min(index % 4,3)*70}ms`);observer.observe(item)}); return ()=>observer.disconnect(); },[route]); }
function useTextMotion(route) { useEffect(() => { const headings=[...document.querySelectorAll('.route-shell h1, .route-shell h2, .route-shell h3')]; headings.forEach((heading)=>{if(heading.dataset.letterMotion)return; heading.dataset.letterMotion='true'; heading.classList.add('letter-fall'); heading.setAttribute('aria-label',heading.textContent.trim()); const walker=document.createTreeWalker(heading,NodeFilter.SHOW_TEXT); const nodes=[]; while(walker.nextNode())nodes.push(walker.currentNode); const characterCount=nodes.reduce((total,node)=>total+[...node.textContent].length,0); let index=0; nodes.forEach((node)=>{const fragment=document.createDocumentFragment(); [...node.textContent].forEach((character)=>{const letter=document.createElement('span'); letter.className='fall-letter'; letter.setAttribute('aria-hidden','true'); letter.style.setProperty('--letter-delay',`${Math.round(index++*1650/Math.max(characterCount-1,1))}ms`); letter.textContent=character===' '?'\u00a0':character; fragment.appendChild(letter)}); node.replaceWith(fragment)}); }); const paragraphs=[...document.querySelectorAll('.route-shell p')]; const reveal=(element)=>element.classList.add('copy-visible'); paragraphs.forEach((paragraph,index)=>{if(paragraph.dataset.copyMotion)return; paragraph.dataset.copyMotion='true'; paragraph.classList.add('copy-fade'); paragraph.style.setProperty('--copy-delay',`${Math.min(index%5,4)*85}ms`);}); if(!('IntersectionObserver' in window)){paragraphs.forEach(reveal);return;} const observer=new IntersectionObserver((entries)=>entries.forEach(entry=>{if(entry.isIntersecting){reveal(entry.target);observer.unobserve(entry.target)}}),{threshold:.1,rootMargin:'0px 0px -16px'}); paragraphs.forEach(paragraph=>observer.observe(paragraph)); return ()=>observer.disconnect(); },[route]); }
function Image({src,alt,className=''}) { const [failed,setFailed]=useState(false); return failed ? <div className={`image-fallback ${className}`} aria-label={alt}>✦</div> : <img className={className} src={src} alt={alt} loading="lazy" onError={()=>setFailed(true)} />; }
function Logo() { return <button className="brand" onClick={()=>navigate('/')}><span className="brand-mark">✦</span><span><strong>TravelMate</strong><small>Your Personal Travel Recommender</small></span></button>; }
function Navbar({favorites,onTheme,theme}) { const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>18); window.addEventListener('scroll',onScroll,{passive:true}); return ()=>window.removeEventListener('scroll',onScroll)},[]); return <header className={`navbar ${scrolled?'scrolled':''}`}><div className="nav-inner"><Logo/><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open?'×':'☰'}</button><nav className={open?'open':''}>{navItems.map(([path,label])=><button key={path} className={window.location.pathname===path?'active':''} onClick={()=>{navigate(path);setOpen(false)}}>{label}</button>)}<button className="theme-toggle" onClick={onTheme} aria-label={`Switch to ${theme==='light'?'dark':'light'} theme`}>{theme==='light'?'☾':'☀'}</button><button className="trips-link" onClick={()=>navigate('/my-trips')}>♡ <span>My Trips</span>{favorites.length>0&&<b>{favorites.length}</b>}</button></nav></div></header>; }
function Footer() { return <footer><div className="footer-inner"><div><Logo/><p>Thoughtful journeys, matched to you.</p></div><div className="footer-links"><button onClick={()=>navigate('/explore')}>Explore India</button><button onClick={()=>navigate('/how-it-works')}>How it works</button><button onClick={()=>navigate('/contact')}>Contact</button></div><span>© 2026 TravelMate · A frontend project</span></div></footer>; }
function Field({number,label,children}) { return <div className="field"><label><i>{number}</i>{label}</label>{children}</div>; }
function PreferenceForm({onSubmit,initial=emptyPreferences}) { const [form,setForm]=useState({...emptyPreferences,...initial}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const update=(key,value)=>setForm({...form,[key]:value}); const toggle=(item)=>update('interests',form.interests.includes(item)?form.interests.filter(x=>x!==item):[...form.interests,item]); const submit=(e)=>{e.preventDefault(); if(!form.budget||!form.days||!form.climate||!form.travelType){setError('Choose a budget, trip length, climate and travel type to continue.');return;} setError(''); setLoading(true); window.setTimeout(()=>onSubmit(form),260);}; return <form className="preference-form" onSubmit={submit}><div className="form-heading"><span>✧ &nbsp; FIND YOUR PERFECT INDIAN DESTINATION &nbsp; ✧</span><h2>Start with what<br/><em>feels right.</em></h2></div><Field number="01" label="State"><select value={form.state} onChange={e=>update('state',e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select></Field><Field number="02" label="Budget (₹)"><div className="option-grid">{budgets.map(x=><button type="button" className={form.budget===x?'selected':''} onClick={()=>update('budget',x)} key={x}>{x}</button>)}</div></Field><Field number="03" label="Number of Days"><div className="option-grid compact">{days.map(x=><button type="button" className={form.days===x?'selected':''} onClick={()=>update('days',x)} key={x}>{x}</button>)}</div></Field><Field number="04" label="Preferred Climate"><div className="option-grid compact">{climates.map(x=><button type="button" className={form.climate===x?'selected':''} onClick={()=>update('climate',x)} key={x}>{x}</button>)}</div></Field><Field number="05" label="Interests (Select one or more)"><div className="interest-grid">{interests.map(x=><button type="button" className={form.interests.includes(x)?'selected':''} onClick={()=>toggle(x)} key={x}><span>{icons[x]}</span>{x}</button>)}</div></Field><Field number="06" label="Travel Type"><div className="travel-grid">{travelTypes.map(x=><button type="button" className={form.travelType===x?'selected':''} onClick={()=>update('travelType',x)} key={x}>{x}</button>)}</div></Field>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button submit-button" type="submit" disabled={loading}>{loading?<><span className="loader"/>Analyzing your preferences…</>:<>⌕ &nbsp; Find my destination</>}</button></form>; }
function IndiaMapVisual() { const [active,setActive]=useState('Rajasthan'); const locations=[['Jammu & Kashmir','Srinagar',50,19],['Rajasthan','Jaipur',36,40],['Uttar Pradesh','Agra',55,39],['West Bengal','Darjeeling',73,48],['Gujarat','Ahmedabad',33,57],['Maharashtra','Mumbai',42,65],['Karnataka','Coorg',52,78],['Kerala','Munnar',49,88],['Tamil Nadu','Ooty',59,87],['Sikkim','Gangtok',74,39]]; const selected=locations.find(([state])=>state===active); return <div className="hero-art map-visual"><div className="map-skyline">✦ &nbsp; · &nbsp; ✦</div><div className="map-title">YOUR INDIA<br/><em>starts here.</em></div><img className="india-map" src="https://upload.wikimedia.org/wikipedia/commons/b/b4/India_outline.svg" alt="Outline map of India"/>{locations.map(([state,city,x,y])=><button className={`map-pin ${active===state?'active':''}`} style={{left:`${x}%`,top:`${y}%`}} key={state} onMouseEnter={()=>setActive(state)} onFocus={()=>setActive(state)} onClick={()=>setActive(state)} aria-label={`${state}, ${city}`}><span/> </button>)}{selected&&<div className="map-popup" style={{left:`${Math.min(selected[2]+4,68)}%`,top:`${Math.max(selected[3]-9,5)}%`}}><small>{selected[0]}</small><b>{selected[1]}</b><span>Explore this region ↗</span></div>}<div className="map-compass">N<br/><span>↑</span></div><div className="art-caption">TRAVEL NOTES / 01<br/><b>Somewhere in India</b></div><a className="map-credit" href="https://commons.wikimedia.org/wiki/File:India_outline.svg" target="_blank" rel="noreferrer">Map outline: CC BY-SA</a></div>; }
function Hero({onSubmit}) { return <section className="hero"><div className="hero-copy"><p className="eyebrow">A little more you, a lot more India</p><h1>Explore India.<br/><em>Find Your Perfect<br/>Destination.</em></h1><p className="hero-intro">28 states. Hundreds of destinations.<br/>One journey made for you.</p><div className="benefits"><div><span>✓</span><p><b>Personalized Recommendations</b><small>Based on your preferences</small></p></div><div><span>₹</span><p><b>Budget Friendly</b><small>Matches your budget perfectly</small></p></div><div><span>♧</span><p><b>Trusted &amp; Reliable</b><small>Handpicked destinations across India</small></p></div></div></div><IndiaMapVisual/><PreferenceForm onSubmit={onSubmit}/></section>; }
function StatsSection() { return <section className="stats-section"><div className="stats-intro"><span className="eyebrow">The map is wide open</span><h2>Made for the<br/><em>curious.</em></h2></div><div className="stats-grid"><div><strong>28</strong><span>states to explore</span><small>From the high Himalayas to the southern coast</small></div><div><strong>50+</strong><span>destinations</span><small>Handpicked places with a story to tell</small></div><div><strong>100%</strong><span>preference-led</span><small>Your trip, your pace, your kind of weather</small></div></div></section>; }
function HowItWorksStrip() { const steps=[['⌖','Choose State','Select a state or search across India'],['☷','Enter Preferences','Tell us your budget, days and interests'],['✺','Smart Matching','We compare your preferences with places'],['☆','Get Recommendations','View top destinations with reasons']]; return <section className="how-strip"><div className="section-label">HOW TRAVELMATE WORKS</div><div className="how-steps">{steps.map(([icon,title,text],index)=><div className="how-step" key={title}><span className="how-icon">{icon}</span><b>{index+1}. {title}</b><small>{text}</small>{index<steps.length-1&&<i>→</i>}</div>)}</div></section>; }
function TopDestinations() { const featured=destinations.slice(0,3); return <section className="top-destinations"><div className="section-head"><div><span className="eyebrow">A little inspiration</span><h2>Top destinations <em>right now.</em></h2></div><button className="text-button" onClick={()=>navigate('/explore')}>View all <span>↗</span></button></div><div className="featured-grid">{featured.map((d,index)=><article className="featured-card" key={d.id} onClick={()=>navigate(`/destination/${d.id}`)}><div><Image src={d.image} alt={d.name}/><span className="featured-score">{95-index*6}% Match</span></div><div className="featured-body"><h3>{d.name}</h3><p>{d.state}</p><small>{d.interests.slice(0,3).join(' · ')} · {d.climate}</small><button className="text-button">Why this destination? <span>ⓘ</span></button></div></article>)}</div></section>; }
function Home({onSubmit}) { return <><main className="home"><Hero onSubmit={onSubmit}/><HowItWorksStrip/><TopDestinations/><StatsSection/><section className="home-band"><div><span className="eyebrow">Start somewhere beautiful</span><h2>There is a version<br/><em>of India for you.</em></h2></div><p>Whether you want mountain air, a plate of something new, or a beach with no plans attached, TravelMate helps you find the place that fits.</p><button className="text-button" onClick={()=>navigate('/explore')}>Browse all states <span>↗</span></button></section></main><Footer/></>; }
function MatchScore({score}) { return <div className={`match match-${score>=80?'high':score>=60?'mid':'low'}`}><strong>{score}%</strong><span>{matchLabel(score)}</span></div>; }
function FavoriteButton({id,favorites,onToggle}) { const active=favorites.includes(id); return <button className={`favorite ${active?'saved':''}`} aria-label={active?'Remove from favorites':'Save destination'} onClick={(e)=>{e.stopPropagation();onToggle(id)}}>{active?'♥':'♡'}</button>; }
function WhyDestination({destination,preferences}) { const matched=preferences.interests?.filter(x=>destination.interests.includes(x))||[]; const reasons=[]; if(preferences.climate&&destination.climate===preferences.climate) reasons.push(`its ${destination.climate.toLowerCase()} climate is exactly what you asked for`); if(matched.length) reasons.push(`it brings together your love of ${matched.join(' and ').toLowerCase()}`); if(preferences.days&&destination.durationRange===preferences.days) reasons.push(`the ${preferences.days.toLowerCase()} rhythm fits naturally`); if(!reasons.length) reasons.push(`it offers a beautifully balanced way to discover ${destination.state}`); return <p className="why"><b>Why this one</b> {destination.name} stood out because {reasons.join(', ')}.</p>; }
function RecommendationCard({destination,index,favorites,onToggle,preferences}) { return <article className="recommendation-card" onClick={()=>navigate(`/destination/${destination.id}`)}><div className="card-image"><Image src={destination.image} alt={destination.name}/><span className="rank">0{index+1}</span><FavoriteButton id={destination.id} favorites={favorites} onToggle={onToggle}/><MatchScore score={destination.score}/></div><div className="card-body"><p className="card-kicker">{destination.state} · {destination.climate}</p><h3>{destination.name}</h3><p>{destination.description}</p><div className="card-meta"><span>◷ {destination.durationRange}</span><span>₹ {destination.budgetRange.replace('₹','')}</span></div><WhyDestination destination={destination} preferences={preferences}/><button className="text-button">Explore place <span>→</span></button></div></article>; }
function Recommendations({preferences,favorites,onToggle}) { const results=useMemo(()=>getRecommendations(destinations,preferences),[preferences]); return <><main className="page recommendations-page"><div className="page-intro"><div><p className="eyebrow">Your travel shortlist</p><h1>Places with<br/><em>your name on them.</em></h1></div><div className="preference-summary"><span>YOUR FILTERS</span><p>{preferences.state} · {preferences.budget} · {preferences.days}</p><p>{preferences.climate} · {preferences.interests.join(' + ')||'Open to discovery'} · {preferences.travelType}</p><button className="text-button" onClick={()=>navigate('/')}>Edit preferences ↗</button></div></div><div className="results-heading"><span>{results.length} considered matches</span><p>Ranked by the things that matter to you.</p></div><div className="recommendation-grid">{results.map((d,i)=><RecommendationCard key={d.id} destination={d} index={i} favorites={favorites} onToggle={onToggle} preferences={preferences}/>)}</div></main><Footer/></>; }
function Explore({favorites,onToggle}) { const [query,setQuery]=useState(''); const filtered=destinationStates.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())); return <><main className="page"><div className="simple-heading"><p className="eyebrow">Take the scenic route</p><h1>Explore <em>India.</em></h1><p>Every state has a different story. Start with the one that catches your eye.</p><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a state..." aria-label="Search states"/></div><div className="state-grid">{filtered.map(state=><article className="state-card" key={state.name} onClick={()=>{const first=destinations.find(d=>d.state===state.name);if(first)navigate(`/destination/${first.id}`)}}><div className="state-art"><span>{state.name.slice(0,2).toUpperCase()}</span></div><div><p className="card-kicker">{state.count} destinations</p><h3>{state.name}</h3><p>{state.description}</p><button className="text-button">See the places <span>→</span></button></div></article>)}</div>{!filtered.length&&<div className="empty-state">No states found. Try another search.</div>}</main><Footer/></>; }
function InfoPage({type}) { const content={
 '/how-it-works':{eyebrow:'A better way to wander',title:<>How it <em>works.</em></>,intro:'A few thoughtful questions. A whole country of possibilities.',body:[['01','Choose your compass','Tell us a state, or leave the map wide open.'],['02','Share your rhythm','Your budget, days, weather and interests shape the search.'],['03','Meet your matches','Our local, browser-based engine weighs every preference.'],['04','Make it yours','Compare the shortlist, save favorites and follow your curiosity.']]},
 '/about':{eyebrow:'The idea behind the map',title:<>India, <em>your way.</em></>,intro:'TravelMate is a frontend travel recommendation project for people who want the planning to feel as personal as the trip.',body:[['01','Personal, not prescriptive','Recommendations are shaped by your preferences, not a one-size-fits-all list.'],['02','India-focused','From Himalayan mornings to coastal evenings, the data stays close to home.'],['03','Simple by design','No accounts, no noise, no black box. Just a clear path to somewhere new.'],['04','Made for curiosity','Use it to plan the trip you have in mind, or discover one you did not.']]},
 '/contact':{eyebrow:'Say hello',title:<>Let’s talk <em>travel.</em></>,intro:'This is a frontend demo, but your note still deserves a thoughtful response.',body:[]}}[type]; const [sent,setSent]=useState(false); return <><main className="page info-page"><div className="simple-heading"><p className="eyebrow">{content.eyebrow}</p><h1>{content.title}</h1><p>{content.intro}</p></div>{type==='/contact'?<form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><span>✦</span><h2>Message received.</h2><p>Thanks! Your message has been recorded for this demo.</p><button type="button" className="text-button" onClick={()=>setSent(false)}>Send another ↗</button></div>:<><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Message<textarea required rows="5" placeholder="Tell us where you want to go..."></textarea></label><button className="primary-button" type="submit">Send message <span>→</span></button></>}</form>:<div className="steps">{content.body.map(([num,title,text])=><article key={num}><span>{num}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div>}</main><Footer/></>; }
function DestinationDetails({id,preferences,favorites,onToggle}) { const d=destinations.find(x=>x.id===id); if(!d)return <NotFound/>; const score=scoreDestination(d,preferences); return <><main className="detail"><button className="back-button" onClick={()=>navigate('/recommendations')}>← Back to recommendations</button><div className="detail-hero"><Image src={d.image} alt={d.name}/><div className="detail-overlay"><p className="eyebrow">{d.state} · {d.climate}</p><h1>{d.name}<em>.</em></h1><FavoriteButton id={d.id} favorites={favorites} onToggle={onToggle}/></div></div><div className="detail-content"><div><p className="detail-description">{d.description}</p><h2>Good to know</h2><div className="detail-facts"><span><b>Budget</b>{d.budgetRange}</span><span><b>Best time</b>{d.bestTime}</span><span><b>Stay</b>{d.durationRange}</span><span><b>Best for</b>{d.interests.slice(0,3).join(' · ')}</span></div><h2>Make a day of it</h2><div className="highlight-list">{d.highlights.map((h,i)=><span key={h}><i>0{i+1}</i>{h}</span>)}</div></div><aside><MatchScore score={score}/><WhyDestination destination={d} preferences={preferences}/><button className="primary-button" onClick={()=>navigate('/explore')}>Find nearby places <span>→</span></button></aside></div></main><Footer/></>; }
function Trips({favorites,onToggle}) { const saved=destinations.filter(d=>favorites.includes(d.id)); return <><main className="page"><div className="simple-heading"><p className="eyebrow">Your saved places</p><h1>My <em>Trips.</em></h1><p>Keep the places that made you pause close at hand.</p></div>{saved.length?<div className="trip-list">{saved.map(d=><article key={d.id}><Image src={d.image} alt={d.name}/><div><p className="card-kicker">{d.state}</p><h2>{d.name}</h2><p>{d.description}</p><button className="text-button" onClick={()=>navigate(`/destination/${d.id}`)}>View destination →</button></div><FavoriteButton id={d.id} favorites={favorites} onToggle={onToggle}/></article>)}</div>:<div className="empty-state"><span>♡</span><h2>Your map is waiting.</h2><p>Save a destination to start building your trip list.</p><button className="primary-button" onClick={()=>navigate('/explore')}>Explore states <span>→</span></button></div>}</main><Footer/></>; }
function NotFound(){return <main className="page empty-state"><span>404</span><h1>Wrong turn.</h1><p>This page is not on our map.</p><button className="primary-button" onClick={()=>navigate('/')}>Back home <span>→</span></button></main>}
export default function App(){ const route=useRoute(); useReveal(route); useTextMotion(route); const [favorites,setFavorites]=useState(()=>{const value=readStoredJSON('travelmate-favorites',[]);return Array.isArray(value)?value:[]}); const [preferences,setPreferences]=useState(()=>{const value=readStoredJSON('travelmate-preferences',emptyPreferences);return value&&typeof value==='object'?{...emptyPreferences,...value,interests:Array.isArray(value.interests)?value.interests:[]}:emptyPreferences}); const [theme,setTheme]=useState(()=>readStoredText('travelmate-theme','light')==='dark'?'dark':'light'); useEffect(()=>writeStored('travelmate-favorites',JSON.stringify(favorites)),[favorites]); useEffect(()=>writeStored('travelmate-preferences',JSON.stringify(preferences)),[preferences]); useEffect(()=>{writeStored('travelmate-theme',theme);document.documentElement.dataset.theme=theme},[theme]); const toggle=(id)=>setFavorites(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]); const submit=(form)=>{setPreferences(form);navigate('/recommendations')}; let content=route==='/'?<Home onSubmit={submit}/>:route==='/explore'?<Explore favorites={favorites} onToggle={toggle}/>:route==='/recommendations'?<Recommendations preferences={preferences} favorites={favorites} onToggle={toggle}/>:route==='/my-trips'?<Trips favorites={favorites} onToggle={toggle}/>:['/how-it-works','/about','/contact'].includes(route)?<InfoPage type={route}/>:route.startsWith('/destination/')?<DestinationDetails id={route.split('/')[2]} preferences={preferences} favorites={favorites} onToggle={toggle}/>:<NotFound/>; return <><Navbar favorites={favorites} theme={theme} onTheme={()=>setTheme(theme==='light'?'dark':'light')}/><div key={route} className="route-shell">{content}</div></>; }
